# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

pool:
  vmImage: "windows-2019"

variables:
  solution: '**/*.sln'
  buildPlatform: 'x86'
  buildConfiguration: 'Final Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

#- task: MSBuild@1
#  inputs:
#    solution: '**/*.sln'
#    platform: '$(buildPlatform)'
#    configuration: '$(buildConfiguration)'

- task: VSBuild@1
  inputs:
    solution: 'NOLF\\NOLF.sln'
    vsVersion: '16.0'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: CopyFiles@2
  inputs:
    SourceFolder: '.\\'
    Contents: |
      NOLF\\ClientRes\\CRes.dll
      NOLF\\ClientShellDLL\\CShell.dll
      NOLF\\ObjectDLL\\Object.lto
    TargetFolder: '$(Pipeline.Workspace)'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Pipeline.Workspace)'
    artifact: '$(buildConfiguration) Files'
